# Generated by Django 5.0.2 on 2024-05-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='null', max_length=100)),
                ('first_name', models.CharField(default='null', max_length=100)),
                ('last_name', models.CharField(default='null', max_length=100)),
                ('dpi', models.CharField(default='null', max_length=13)),
                ('age', models.DateField(default=datetime.datetime.now)),
                ('tel', models.CharField(blank=True, default='null', max_length=8)),
                ('email', models.EmailField(default='correo@gmail.com', max_length=254)),
                ('password', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
